apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

namePrefix: dev-

resources:
- ../../base
- namespace.yaml

commonLabels:
  app: devnginx
  
patches:
 - path: patch.yaml

