apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-app-container
        image: vimleshmourya/my-nginx-css-template:v1
