apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

resources:
- ../../base
- namespace.yaml

commonLabels:
  app: nginx
  
patches:
 - path: patch.yaml